// <auto-generated />
namespace DiplomApp.Data.Migrations.DevicesMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SwitchOptionsCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SwitchOptionsCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201904221648122_SwitchOptionsCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
